# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_profile_picture', models.FileField(upload_to=b'')),
                ('user_age', models.IntegerField(default=20)),
                ('user_profession', models.CharField(max_length=50)),
                ('user_tags', models.CharField(max_length=1000)),
            ],
        ),
    ]
