# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_picture',
            field=models.CharField(max_length=1000),
        ),
    ]
