# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20170128_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=100)),
                ('developer_logo', models.CharField(max_length=1000)),
                ('developer_headquarters', models.CharField(max_length=1000)),
                ('developer_tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_tags',
            field=models.CharField(max_length=100),
        ),
    ]
