# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20170128_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_logo',
            field=models.FileField(max_length=1000, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_picture',
            field=models.FileField(max_length=1000, upload_to=b''),
        ),
    ]
