# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20170128_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
