# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=100)),
                ('developer_logo', models.FileField(upload_to=b'')),
                ('developer_headquarters', models.CharField(max_length=100)),
                ('developer_tags', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_headquarters',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
