# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_developer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
