# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20170131_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='developer_address',
            field=models.CharField(default='Professional address', max_length=1000),
        ),
        migrations.AddField(
            model_name='developer',
            name='developer_contact',
            field=models.CharField(default='Office(No.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_tags',
            field=models.CharField(default='Enter details separated by comma', max_length=100),
        ),
    ]
