# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20170131_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_tags',
            field=models.CharField(default='Separate by comma', max_length=100),
        ),
    ]
