# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20170131_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_contact',
            field=models.CharField(default='', max_length=100),
        ),
    ]
